### ISSUE TITLE
add meta tag to index.html head

### ISSUE THREAD

**Issue by bbbjihan** [uchumu/mudda#39]

**Comment by bunzzeok** [comment]
<meta
      name="description"
      content="우리의 추억을 무따"
    />
    <meta name="robots" content="index,follow" />
    <meta property="og:title" content="무따" />
    <meta property="og:site_name" content="mudda" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="https://mudda.kr/" />
    <meta property="og:image" content="_무따 디자인" />
    <meta
      property="og:description"
      content="우리의 추억을 무따.. 우.무.추 무따"
    />
    <meta itemprop="name" content="무따" />
    <meta
      itemprop="description"
      content="우리의 추억을 무따.. 우.무.추 무따"
    />
    <meta itemprop="image" content="우리의 추억을 무따.. 우.무.추 무따" />
    <meta name="keywords" content="무따" />

**Comment by bunzzeok** [comment]
```javascript

<meta
      name="description"
      content="우리의 추억을 무따"
    />
    <meta name="robots" content="index,follow" />
    <meta property="og:title" content="무따" />
    <meta property="og:site_name" content="mudda" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="https://mudda.kr/" />
    <meta property="og:image" content="_무따 디자인" />
    <meta
      property="og:description"
      content="우리의 추억을 무따.. 우.무.추 무따"
    />
    <meta itemprop="name" content="무따" />
    <meta
      itemprop="description"
      content="우리의 추억을 무따.. 우.무.추 무따"
    />
    <meta itemprop="image" content="우리의 추억을 무따.. 우.무.추 무따" />
    <meta name="keywords" content="무따" />


```
